### ISSUE TITLE
请问下函数有发布到 npm吗? 没看到函数的安装文档呢

### ISSUE THREAD

**Issue by itmier** [chaxus/ran#176]

**Comment by chaxus** [comment]
有的，首页的readme写了函数打的包是ranuts。npm包同名，可以搜到，不过还是放个链接在这里：https://www.npmjs.com/package/ranuts

**Comment by itmier** [comment]
谢谢,  package 里看到 ranuts 的 readme 了
发现一个小问题: ran项目里 readme 上的 ranuts 下你放的链接 404 了

**Comment by chaxus** [comment]
啊，确实，可以帮忙提个pr修改下嘛，非常感谢[捂脸]，链接是这个：https://chaxus.github.io/ran/src/ranuts
或者我晚上下班提一下pr🌹🌹🌹

**Comment by chaxus** [comment]
看你的时间都可以的，感谢提出的问题

**Comment by itmier** [comment]
好的 等我下班~
