### ISSUE TITLE
预览页面关闭之后无法再次打开

### ISSUE THREAD

**Issue by trentyc** [chaxus/ran#214]
![微信截图_20240221172704](https://github.com/chaxus/ran/assets/62059894/93bea2de-34ae-41fe-a6fb-d07ce21d172d)

**Comment by chaxus** [comment]
![image](https://github.com/chaxus/ran/assets/92639172/3e8b3230-63a8-43f3-963b-e2ef04bc30ff)

有绑定点击事件，点击`preview`元素后可以重新打开。

或者您更希望什么交互方式呢。

**Comment by trentyc** [comment]
第一次使用的时候疑惑不能再次打开，已采用 showPreview 方法了，感谢解答。

**Comment by chaxus** [comment]
> 第一次使用的时候疑惑不能再次打开，已采用 showPreview 方法了，感谢解答。

这是一个非常好的问题，我认为文档上可能存在表述不清的情况。您是否方便修改下文档呢？在项目的这个路径：ran/packages/docs/cn/src/ranui/preview/index.md

把  

```html
<r-preview id="fhdjskafk"></r-preview> 
```

添加`重新打开`的文字

```html
<r-button><r-preview id="fhdjskafk">重新打开</r-preview></r-button> 
```

我感觉就可以了

如果您这边有时间的话，可以提一个pr，我去合并下。没时间也没关系，我就后面去改一下文档的例子
